Proximity
tataratat/splinepy pull request #15
Opened 2022-05-23 06:54 UTC by j042

# Overview
(WIP) working prototype of finding closest parametric coordinates using so called __j<sup>2</sup>(f<sub>0</sub>)__ algorithm.
Will explain more before merge.

2022-05-23 06:55 UTC, j042 commented
@jzwar

2022-05-30 03:44 UTC, j042 commented on src/splinelib_ext/arrutils.hpp
> +      // TODO: since it is nested, we can just do once?
yes

2022-05-30 03:58 UTC, j042 commented on src/splinelib_ext/arrutils.hpp
> +    std::cout << "x" << i <<": " << x[i] << " ";
rm

2022-06-13 10:23 UTC, jzwar requested changes
Some additional points
1. There seems to be no use of the newly provided functions in spinpy's python interface.
2. Templatize all functions please
3. Revisit the c++ naming conventions

2022-06-13 10:23 UTC, jzwar commented on src/splinelib_ext/nurbspl.hpp
> +  /***************************************************************************/
What the `C` is that??

2022-06-13 10:23 UTC, jzwar commented on src/splinelib_ext/nurbspl.hpp
> +      std::cout << "System Matrix: A | b  (d2jdu2 | djdu)\n";
Is user output necessary

2022-06-13 10:23 UTC, jzwar commented on src/splinelib_ext/nurbspl.hpp
> +      if (std::abs(prevnorm - curnorm) < tolerance
Will never be fulfilled on first iteration. Although the first iteration can be sufficient. If

2022-07-08 11:00 UTC, j042 commented on src/helpers.hpp
> +void nthread_execution(
`MultiThreadExecutionButIfGivenNThreadIsEqualToOneItWillNotCreateThreads`

2022-07-12 12:23 UTC, j042 commented on src/helpers.hpp
> +    tpool.emplace_back(std::thread{f, i * chunk_size, (i + 1)*chunk_size});
taf!

2022-07-12 12:23 UTC, j042 commented on src/helpers.hpp
> +        std::thread{f, (nthread - 2) * chunk_size, total}
good catch, thanks

2022-07-12 12:24 UTC, j042 commented on src/helpers.hpp
> +
k

2022-07-15 09:36 UTC, j042 commented
thanks for the comments, I will work on those! closing this one for now.

2022-07-15 09:36 UTC, closed without merging