Update README.md file
tataratat/splinepy pull request #156
Opened 2023-05-30 13:23 UTC by deltaLuki

# Overview
The example (Quick Start) in the README.md file no longer worked. There were typos and other errors. These bugs have been fixed here. 
Since pre-commit didn't work for me, I downgraded mirrors-clang-formats to 15.0.7

## Addressed issues
*  #155 

## Showcase

## Checklists
* [x] Documentations are up-to-date.
* [x] Added example(s)
* [x] Added test(s)

2023-05-30 14:13 UTC, j042 requested changes
please don't change the pre-commit.  
can you please keep cps in init, and change grid_cps using multi_index?

2023-05-30 14:31 UTC, jzwar commented
> please don't change the pre-commit. can you please keep cps in init, and change grid_cps using multi_index?

I second that. This is exactly what the multi-index class was built for. Thank you still for fixing the typo

2023-05-31 09:06 UTC, deltaLuki commented
> 
Should I use the cps from the bspline with multi_index to generate the grid_cps?
 
```python
grid_cps = bspline.cps[bspline.multi_index[:, :]]
assert np.allclose(
    bspline.control_points,
    grid_cps
)
```

2023-06-07 10:41 UTC, jzwar commented
I took the liberty to implement the multi-index request by @j042.

2023-06-07 10:56 UTC, j042 reviewed
Thanks!

2023-06-07 10:56 UTC, j042 commented on README.md
> +grid_cps = np.empty((6, 2))
```suggestion
grid_cps = np.empty(bspline.control_points.shape)
```

2023-06-07 10:56 UTC, j042 commented on README.md
> +        [0.0, 0.0],  # [0, 0]
```suggestion
        [0.0, 0.0],  # [0, 0] (control grid index)
```
maybe a hint like this?

2023-06-07 11:12 UTC, jzwar commented on README.md
> +        [0.0, 0.0],  # [0, 0]
Good idea

2023-06-07 11:13 UTC, j042 approved these changes

2023-06-07 11:14 UTC, merged