Add drilled tile rebased
tataratat/splinepy pull request #316
Opened 2023-12-04 11:50 UTC by mkofler96

# Overview
added new microtile

## Addressed issues
.

## Showcase
A "short" example to highlight the (new) feature
```
# %%
import splinepy as sp
import gustaf as gus
import numpy as np
import vedo

# comment this line to visualize within the notebook (limited functionalities)
vedo.settings.default_backend = "vtk"

# %%
microstructure = sp.microstructure.Microstructure()
microstructure.deformation_function = sp.Bezier(
    degrees=[1, 1],
    control_points=[[0, 0], [0.5,0], [0, 1], [0.5, 1]],
)

angles = np.linspace(-np.pi/2+0.01,np.pi/2-0.01, 10)

tiles = []
for a in angles:
    parameters = np.ones((1,1))*a
    my_microtile = sp.microstructure.tiles.DrilledCrossTile1D()
    showable_tile = my_microtile.create_tile(parameters=parameters)
    tiles.append(showable_tile[0])
gus.show(*tiles, control_points=False)

# %%
# Parameter spline
para_s = sp.BSpline(
    degrees=[1, 1],
    knot_vectors=[[0, 0, 1, 1], [0, 0,0.5, 1, 1]],
    control_points=[[1], [0], [0], [0] , [1], [0]],
)

def pf_curved_tile(x):
    """
    Parametrization Function (determines thickness)
    """
    
    return np.pi/2*para_s.evaluate(x)

# %%
ms = sp.microstructure.Microstructure()
ms.deformation_function = sp.Bezier(
    degrees=[1, 1],
    control_points=[[0, 0], [0.5,0], [0, 1], [0.5, 1]],
)

my_microtile = sp.microstructure.tiles.DrilledCrossTile1D()
showable_tile = my_microtile.create_tile()

#ms.microtile = showable_tile[0]
ms.microtile = my_microtile
ms.tiling = [8, 16]
ms.parametrization_function = pf_curved_tile
ms.show(control_points=False, title="2D Lattice Microstructure", lighting="off")

```

## Checklists
* [x] Documentations are up-to-date.
* [ ] Added example(s)
* [ ] Added test(s)

2023-12-04 11:52 UTC, jzwar approved these changes
LGTM, thanks for the update!

2023-12-04 13:05 UTC, j042 requested changes

2023-12-04 13:05 UTC, j042 commented on splinepy/microstructure/tiles/drilled_cross_beams.py
> +        self._dim = 2
_para_dim is missing here

2023-12-06 13:17 UTC, mkofler96 commented
First it was called DrilledCrossTile1D, but Jacques suggested to give it another name:

The name of the file should be in `snake_case`, please. Also, consider naming the tile
`DrilledCrossBeams` or `TwistedCrossBeams` to avoid confusion...

_Originally posted by @jzwar in https://github.com/tataratat/splinepy/issues/294#issuecomment-1810012860_

2023-12-06 13:18 UTC, j042 commented
@

> First it was called DrilledCrossTile1D, but Jacques suggested to give it another name:
> 
> The name of the file should be in `snake_case`, please. Also, consider naming the tile `DrilledCrossBeams` or `TwistedCrossBeams` to avoid confusion...
> 
> _Originally posted by @jzwar in [#294 (comment)](https://github.com/tataratat/splinepy/pull/294#issuecomment-1810012860)_

so, `Cross1D`? @jzwar

2023-12-11 16:05 UTC, j042 commented
@jzwar don't we already have `Cross2D`/`Cross3D`? However, I guess this is `X`. What about `X`?

2023-12-14 12:27 UTC, j042 commented
as `X` is not recommended class name, let's go with `Chi`

2023-12-19 08:47 UTC, j042 approved these changes
Thanks!

2023-12-19 09:00 UTC, merged